name: "Bob The Builder"

on:
  push:
    branches: [ next ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:buster 
    steps:
      - run: git clone https://github.com/batbin-org/frontend /frontend
      - run: cd /frontend && yarn && yarn build
